version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /dynamodblocal
    volumes:
      - ./dynamodblocal:/dynamodblocal
    ports:
     - "8000:8000"

 
  airtable-stub:
    build:
      context: ./airtable-local
      dockerfile: Dockerfile
    ports:
      - 8085:8080

  address-api-stub:
    build:
      context: ./address-api-local
      dockerfile: Dockerfile
    ports:
      - 8086:8080