version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

executors:
  build-and-test:
    docker:
      - image: circleci/node:12.13-browsers
      - image: ./airtable-local
        ports: 8085:8080
      - image: circleci/dynamodb
        entrypoint: ['java', '-Xmx1G', '-jar', 'DynamoDBLocal.jar', '-sharedDb']

jobs:
  build-and-test:
    executor: build-and-test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: CYPRESS_CACHE_FOLDER=~/repo/cypress_cache yarn install --frozen-lockfile
      - run:
          name: Build the application
          command: |
            export NEXT_PUBLIC_API_URL=http://localhost:3000/api
            yarn build
      - run:
          name: Run unit tests
          command: yarn run unit-test
      - run:
          name: Run linting
          command: yarn lint
      - aws-cli/setup:
          aws-access-key-id: CYPRESS_AWS_ACCESS_KEY_ID
          aws-secret-access-key: CYPRESS_AWS_SECRET_ACCESS_KEY
          aws-region: CYPRESS_AWS_REGION
      - run:
          name: Create local DynamoDB vulnerabilities table
          command: aws dynamodb create-table --cli-input-json file://./config/tables/vulnerabilities.json --endpoint-url http://localhost:8000 > /dev/null
      - run:
          name: Run integration tests
          command: |
            export NEXT_PUBLIC_API_URL=http://localhost:3000/api
            export VULNERABILITIES_TABLE_NAME=vulnerabilities
            export AIRTABLE_API_KEY=${AIRTABLE_API_KEY_INTEGRATION}
            export AIRTABLE_BASE_ID=baseId123
            export AIRTABLE_TABLE_NAMES=${AIRTABLE_TABLE_NAMES_INTEGRATION}
            export AIRTABLE_BASE_URL=AIRTABLE_BASE_URL
            export ADDRESSES_API_KEY=${ADDRESSES_API_KEY}
            export ADDRESSES_API_URL=${ADDRESSES_API_URL}
            export HOTJAR_ID=${HOTJAR_ID}
            export ALLOWED_GROUPS=xx
            export NEXT_PUBLIC_SINGLEVIEW_URL=https://staging-singleview.hackney.gov.uk
            CYPRESS_CACHE_FOLDER=~/repo/cypress_cache yarn run int-test
      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

  deploy:
    executor: aws-cli/default
    working_directory: ~/repo
    parameters:
      stage_name:
        type: string
      API_URL:
        type: string
      GTM_ID:
        type: string
      SINGLEVIEW_URL:
        type: string
      aws-access-key-id:
        type: env_var_name
      aws-secret-access-key:
        type: env_var_name
      AWS_CERTIFICATE_ARN:
        type: string
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: << parameters.aws-access-key-id >>
          aws-secret-access-key: << parameters.aws-secret-access-key >>
          aws-region: AWS_REGION
      - run: sudo yarn global add serverless
      - run:
          name: deploy
          command: |
            export NEXT_PUBLIC_API_URL=<< parameters.API_URL >>
            export NEXT_PUBLIC_GTM_ID=<< parameters.GTM_ID >>
            export NEXT_PUBLIC_SINGLEVIEW_URL=<< parameters.SINGLEVIEW_URL >>
            export AWS_CERTIFICATE_ARN=<< parameters.AWS_CERTIFICATE_ARN >>
            yarn
            yarn build
            yarn --production=true
            sls deploy -s << parameters.stage_name >>

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-and-test
      - deploy:
          name: deploy-staging
          stage_name: staging
          API_URL: ${NEXT_PUBLIC_API_URL_STAGING}
          aws-access-key-id: AWS_ACCESS_KEY_ID_STAGING
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_STAGING
          AWS_CERTIFICATE_ARN: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
          GTM_ID: ${NEXT_PUBLIC_GTM_ID}
          SINGLEVIEW_URL: ${NEXT_PUBLIC_SINGLEVIEW_URL_STAGING}
          filters:
            branches:
              only: master
          requires:
            - build-and-test
      - permit-deploy-production:
          type: approval
          requires:
            - deploy-staging
      - deploy:
          name: deploy-production
          stage_name: production
          API_URL: ${NEXT_PUBLIC_API_URL_PRODUCTION}
          aws-access-key-id: AWS_ACCESS_KEY_ID_PRODUCTION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_PRODUCTION
          AWS_CERTIFICATE_ARN: arn:aws:acm:us-east-1:153306643385:certificate/71728a39-cd3e-4570-a440-e87f84ef9a0d
          GTM_ID: ${NEXT_PUBLIC_GTM_ID}
          SINGLEVIEW_URL: ${NEXT_PUBLIC_SINGLEVIEW_URL_PRODUCTION}
          requires:
            - permit-deploy-production
